# TODO: figure out why "convert" doesn't work for name.
name: integration_test
version: 0.7.5
description: A package testing ODW packages
author: Jim Philbin <jfphilbin@gmail.com>

homepage: https://github.com/OpenDICOMweb/integration_test

environment:
  sdk: ^2.0.0

dependencies:
  args: any
  batch_job:
    path: C:/odw/batch_job
    version: ^0.7.0
  converter:
    path: C:/odw/sdk/converter
    version: ^0.7.5
  core:
    path: C:/odw/sdk/core
    version: ^0.7.5
  io_extended:
    path: C:/odw/sdk/io_extended
    version: ^0.7.2

dev_dependencies:
  benchmark_harness: any
  grinder: ^0.8.0
  test:  any
  test_tools:
    path: C:/odw/test_tools
    version: ^0.7.5



